### ISSUE TITLE
Total size of workspace

### ISSUE THREAD

**Issue by harshfadiya** [databrickslabs/migrate#173]
I want to find the total size of workspace. It should include all the available components (like users, groups, instance profiles, notebooks, secrets, Meta-store, etc) sizes. I want to know do we have any API which we can use to get the desired result ? If yes, can you please suggest the API and it's behaviour or is there any other possible workaround ?

**Comment by mrchristine** [comment]
There's no public api to do this today and it's not a simple problem as the artifacts are not a single entity stored in an object store. There are estimates that give an understanding of the size of the workspace to migrate, e.g. https://github.com/databrickslabs/migrate/blob/master/data/workspace_migration_analysis.py 
I'll close this out since there's no method to accomplish this now or in the near term.
