### ISSUE TITLE
Table ACL failure with empty database

### ISSUE THREAD

**Issue by mrchristine** [databrickslabs/migrate#183]
If there's no tables / views in a database, we get an empty json response which triggers an error. 
We'll add a fix for this.

**Comment by mrchristine** [comment]
@tomidatabricks can you help with this?

**Comment by tomidatabricks** [comment]
I think we identified what the issue is: in 
 https://github.com/databrickslabs/migrate/blob/master/data/notebooks/Export_Table_ACLs.py
 in the last cell:
```
 # DBTITLE 1,Write total_num_acls and num_errors to the notebook exit value
totals_df = (spark.read
      .format("JSON")
      .load(output_path)
      .selectExpr(
         "sum(1) AS total_num_acls"
        ,"sum(CASE WHEN Principal = 'ERROR_!!!' THEN 1 ELSE 0 END) AS num_errors")
     )
```

If we export an empty database, the json files is empty, so no schema can be deducted from the data,
so there is no "Principal" column.

The solution I am planning to add, is the provide an explicit schema - this is what I should have done
in the first place

**Comment by tomidatabricks** [comment]
We had a call with the team that ran into this issue. And we found that in the workspace there were no Table ACL rules defined at all, so exporting an empty list of TableACL rules is correct. (The client was not aware they had no ACLS, as the person importing and exporting the rules was the not the same person maintaining the rules)
This is an edge case I missed when writing the original code.
The fix I am applying will instead of providing a fixed schema (which would have to be maintained) check for dataframe with with zero records or a single record with zero fields and return the counts of zero rules and zero errors instead.
